[workspace]
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]
platforms = ["win-64", "linux-64", "osx-arm64", "osx-64"]
preview = ["pixi-build"]

[dependencies]
pms_py = { path = "." }
pms = { path = "pms" }
matplotlib = ">=3.10.1,<4"
numpy = ">=2.2.4,<3"
nanobind = "==2.7.0"


[tasks]
start = "rich-example-main"
build = 'cd pms && mkdir -p build && cd build && cmake .. && cmake --build . -j$(nproc)'
dataset_cpp = 'pms/build/dataset /home/neverorfrog/code/planar-monocular-slam/data'
stubgen-pms = "python -m nanobind.stubgen -m pms"

[package]
name = "pms_py"
version = "0.1.0"

[package.build]
backend = { name = "pixi-build-python", version = "0.1.*" }

[package.host-dependencies]
hatchling = "==1.26.3"

[package.run-dependencies]
rich = "13.9.*"

[activation.env]
LD_LIBRARY_PATH = "${CONDA_PREFIX}/lib:$LD_LIBRARY_PATH"
PYTHONPATH = "${CONDA_PREFIX}/lib/python3.12/site-packages:$PYTHONPATH"
