[workspace]
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]
platforms = ["win-64", "linux-64", "osx-arm64", "osx-64"]
preview = ["pixi-build"]

[dependencies]
pms_py = { path = "." }
pms = { path = "pms" }
matplotlib = ">=3.10.1,<4"
numpy = ">=2.2.4,<3"
nanobind = "==2.7.0"
tqdm = ">=4.67.1,<5"
gtest = ">=1.17.0,<2"
cmake = ">=3.20"
make = "*"

[tasks]
build = 'cd pms && mkdir -p build && cd build && cmake .. && cmake --build . -j$(nproc)'
build-tests = 'cd pms && mkdir -p build && cd build && cmake .. -DBUILD_TESTS=ON && cmake --build . -j$(nproc)'
find-tests = { depends-on = ["build-tests"], cmd = 'cd pms/build/test && ctest --output-on-failure' }
tests = { depends-on = ["build-tests"], cmd = 'cd pms/build/test && ./pms_tests' }
stubgen-pms = "python -m nanobind.stubgen -m pms"

[package]
name = "pms_py"
version = "0.1.0"

[package.build]
backend = { name = "pixi-build-python", version = "0.1.*" }

[package.host-dependencies]
hatchling = "==1.26.3"

[package.run-dependencies]
rich = "13.9.*"

[activation.env]
LD_LIBRARY_PATH = "${CONDA_PREFIX}/lib:$LD_LIBRARY_PATH"
PYTHONPATH = "${CONDA_PREFIX}/lib/python3.12/site-packages:$PYTHONPATH"
