[workspace]
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]
platforms = ["win-64", "linux-64", "osx-arm64", "osx-64"]
preview = ["pixi-build"]

[dependencies]
rich_example = { path = "." }
pms = { path = "pms" }
matplotlib = ">=3.10.1,<4"
numpy = ">=2.2.4,<3"

[tasks]
start = "rich-example-main"
visualize = "python rich_example/visualization.py"

[package]
name = "rich_example"
version = "0.1.0"

[package.build]
backend = { name = "pixi-build-python", version = "0.1.*" }

[package.host-dependencies]
hatchling = "==1.26.3"

[package.run-dependencies]
rich = "13.9.*"
