[project]
dependencies = ["rich"]
name = "pms_py"
requires-python = ">= 3.11"
scripts = { rich-example-main = "pms_py:main" }
version = "0.1.0"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]
